### ISSUE TITLE
Support for up to 6 layers

### ISSUE THREAD

**Issue by skaldesh** [UltimateHackingKeyboard/firmware#176] opened 2018-09-19 10:24 UTC
Hello!  
I have a feature request. I am using the [neo2 keyboard layout](https://neo-layout.org/), which uses 6 layers. As far as the UHK team told me via email, the UHK only supports 4 layers.  
I get away right now with 4 layers, since luckily the first 4 are the ones I use 99% of my time. However, it would be cool if the UHK supported 6 layers.

Is this something you would consider?

**Comment by mondalaci** [comment] 2018-09-19 12:09
Yes. This is a duplicate of https://github.com/UltimateHackingKeyboard/agent/issues/617 so I'm closing it.

**Closed as completed by mondalaci** 2018-09-19 12:09 UTC
