### ISSUE TITLE
alt + tab issues when alt comes from a secondary role and tab has a secondary role

### ISSUE THREAD

**Issue by UndeadKernel** [UltimateHackingKeyboard/firmware#213] opened 2019-03-15 16:33 UTC
If `alt` is triggered from a secondary role and if `tab` has a secondary role, `alt + tab` does not work.

See the following setup:
![Screenshot_20190315_172823](https://user-images.githubusercontent.com/6165006/54446726-e6af2980-4747-11e9-92ee-013c3d8a8b7a.png)
Notice that `left space` has the secondary role of `LAlt` and that `tab` has the secondary role of `Mod`. If `right space` is held and `tab` is tapped (not hold), nothing happens.

**Comment by mondalaci** [comment] 2019-03-15 19:23
Duplicate of #198.

**Closed as completed by mondalaci** 2019-03-15 19:23 UTC
