### ISSUE TITLE
Keybinding resets to default on unplug

### ISSUE THREAD

**Issue by alethiophile** [UltimateHackingKeyboard/firmware#427] opened 2021-11-22 21:42 UTC
I have the keycluster module attached, and rebind the left key to another Super. Using Agent 1.5.16 and firmware 8.10.12, when I both unplug the keyboard and detach the module from the keyboard, the keymap resets to default and that key starts registering as backspace. This is not visible in the agent; looking at the keyboard diagram in the agent view, it still shows that key as Super. I can fix the problem by re-saving the keymap to the keyboard (after doing a no-op rebind to make the option appear in the interface).

The problem does not occur after only detaching the module or unplugging the keyboard, only if I do both. Unfortunately, this is my normal procedure when I carry the keyboard around, so the problem shows up pretty regularly.

**Comment by mondalaci** [comment] 2022-01-09 19:23
Very sorry for the late follow-up!

This issue is a duplicate of #361, so I'm closing this one.

**Closed as completed by mondalaci** 2022-01-09 19:23 UTC
