### ISSUE TITLE
Track-point module being off-center after light usage

### ISSUE THREAD

**Issue by soraxas** [UltimateHackingKeyboard/firmware#436] opened 2021-12-27 03:45 UTC
My track-point module had arrived (works great btw!) and I am experiencing some issues with it.

The track-point always begins to experience self-moving after a while (the center point calibration had been offset?). Something that I've observed are:
- This can happen multiple times within a few hours during sessions that I use the trackpoint.
- This happens frequently when I use the trackpoint for scrolling (pressing `mod` key). Probably because in these use cases, we will put constant pressure to the point for an extended period of time
- This is immediately fixable by unplugging and plugging it back (re-calibrate itself0
- ~When this happens, it's always self-moving to the top left direction. Not sure if this is important, but its just my observation.~ (I take this back, it just happened to me in the down direction, probably correlated to the direction of which I constantly hold the pressure)

While this can be workarounded by unplugging and plugging it back, I would still prefer to have it works more reliably. Hopefully this is addressable from the firmware level thanks!

**Comment by mondalaci** [comment] 2021-12-27 13:18
Closing this issue as a duplicate of #382. Please feel free to discuss your findings there.

**Closed as completed by mondalaci** 2021-12-27 13:18 UTC
