### ISSUE TITLE
Feature Request: key backlight killswitch

### ISSUE THREAD

**Issue by dustinpaluch** [UltimateHackingKeyboard/firmware#433] opened 2021-12-22 04:33 UTC
Similar to #426, I'd like to be able to bind a key on my fn layer that toggles the backlight on or off.
Thank you for your consideration.

**Comment by mondalaci** [comment] 2022-03-27 09:27
Closing as a duplicate of #437.

**Closed as completed by mondalaci** 2022-03-27 09:27 UTC
