### ISSUE TITLE
oneShot of a layer does not honor modifiers and also not what is defined on a modifier layer (for example the Shift layer)

### ISSUE THREAD

**Issue by rpnfan** [UltimateHackingKeyboard/firmware#634] opened 2023-07-12 19:17 UTC
Example for the first case: oneShot holdLayer fn2 will work as expected when hold, but not when tapped, for example on the m-key (qwerty) I get ] instead of }

attached my config to reproduce the problems described. Using the default keymap I can not access the : character which is defined on the shifted qwerty-c key when trying to use oneShot shift.
[UserConfiguration (2).zip](https://github.com/UltimateHackingKeyboard/firmware/files/12031451/UserConfiguration.2.zip)

**Comment by kareltucek** [comment] 2023-07-13 19:12
> Using the default keymap I can not access the : character which is defined on the shifted qwerty-c key when trying to use oneShot shift.

In this case your macro has to read `oneShot holdKey iS-`. For more information search https://github.com/UltimateHackingKeyboard/firmware/blob/master/doc-dev/reference-manual.md for "composition mode".

> Example for the first case: oneShot holdLayer fn2 will work as expected when hold, but not when tapped, for example on the m-key (qwerty) I get ] instead of }

I see. I can clearly reproduce this, and it puzzles me why this would not work.

**Comment by kareltucek** [comment] 2023-07-13 19:46
Should be fixed by #635.

Thanks for report!

**Comment by rpnfan** [comment] 2023-07-13 20:14
Thanks for the explanation on "composition mode", that works indeed. Also great you found where the other case went wrong and could fix it. :-)

**Closed as completed** 2023-07-14 18:20 UTC

**Comment by rpnfan** [comment] 2023-07-15 23:00
Just a question. Does the patch also work, when a dead key is used before? With the US international layout Shift-' will produce the dead " and after pressing for example A (thus again Shift-a) will produce Ä.

**Comment by kareltucek** [comment] 2023-07-16 07:28
~I doubt that. I assume the shift would have to be held for next two keys (the dead key and the a key)? And since uhk has no idea which scancode are dead keys according to the host OS, it does not know that in that case one the user expects actually two shots.~

Actually I don't understand the question, since the user may want any of the four shift combinations ( I assume dead key does a different thing when shifted compared to not shifted). Therefore it only makes sense to strictly apply oneshot to one next key, and in that case it of course works since host OS processes deadness of keys, not keyboard.

**Comment by rpnfan** [comment] 2023-07-27 17:59
Just checked with 10.1 and indeed it works as expected. The shifted dead key is correctly triggered. :-)
