### ISSUE TITLE
High CPU usage on Macs

### ISSUE THREAD

**Issue by jwr** [UltimateHackingKeyboard/firmware#428] opened 2021-11-23 09:55 UTC
Plugging in a UHK into a Mac causes the `com.apple.AppleUserHIDDrivers` process to continuously consume between 6 and 10% of CPU. Unplugging the UHK causes the CPU usage to immediately fall to 0.5% or so.

Reproduced on two different computers (a MacBook Pro and and iMac) using Mac OS Monterey and Big Sur, with firmware 8.10.12. and 8.10.10 at least, and with UHK1 and UHK2. The problem is likely not new at all.

**Comment by mondalaci** [comment] 2021-11-23 11:51
Duplicate of #390. I've recently found a developer who has deep knowledge of USB-HID, and he's expected to resolve this issue soon.

**Closed as completed by mondalaci** 2021-11-23 11:51 UTC
