### ISSUE TITLE
Can't use secondary role on letters

### ISSUE THREAD

**Issue by emanuelefirmani** [UltimateHackingKeyboard/firmware#229] opened 2019-06-26 11:10 UTC
I configured secondary roles for A, O, E, U, H, T, N, S (home row of Dvorak layout)
When I type fast, lots of key presses are lost. 
UHK Agent 1.2.12 on Windows

**Comment by kareltucek** [comment] 2019-06-26 13:22
Please see #207 

TLDR: use the variant of secondary role mechanism implemented either in mine or p4elkin's firmware fork:
- p4elkin's has more advanced algorithm and does not need any complex configuratin
- on my fork, you will have to create special macros for all secondary roles you intend to use. As a tradeoff, there are other features which can solve your other two issues.

**Comment by mondalaci** [comment] 2019-06-28 23:10
Closing this as a duplicate of #207.

**Closed as completed by mondalaci** 2019-06-28 23:10 UTC
